version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout

      - restore_cache:
          name: Restore bundle cache
          keys:
            - acts-as-tracked-dependencies

      - run:
          name: Install Bundler
          command: gem install bundler

      - run:
          name: Bundle Install
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          name: Store bundle cache
          paths:
            - ./vendor/bundle
          key: hermes-dependencies

      - run:
          name: Rubocop check
          command:  bundle exec rubocop
